language: python
python:
  - "3.6"
install: "pip install Cython --install-option=\"--no-cython-compile\""
script: 
  - ./build_cython.sh
  - python -m unittest -v tests/tests_hex_lib.py
  - python -m unittest -v tests/tests_utils.py
