# flake8: noqa

# Common actions
L_MOVE = _('move')
L_ROTATE = _('rotate')
L_END_TURN = _('end_turn')
L_UNDO_MOVE = _('undo_move')


# Battle log
L_LOG_BATTLE_STARTED = _('Battle Started')
L_LOG_NEW_TURN = _('New turn started [{}]')
L_LOG_ACTION = _('Action: {} {}')


# Game UI
L_UI_TOGGLE_SELECTED_REACHABLES = _('L_UI_TOGGLE_SELECTED_REACHABLES')
L_UI_TOGGLE_OTHERS_REACHABLES = _('L_UI_TOGGLE_OTHERS_REACHABLES')


# Menus
L_MENU_MAIN_MENU = _('L_MENU_MAIN_MENU')
L_MENU_CHESS_DEMO = _('L_MENU_CHESS_DEMO')
L_MENU_FEATURES_DEMO = _('L_MENU_FEATURES_DEMO')
L_MENU_CAMPAIGN = _('L_MENU_CAMPAIGN')
L_MENU_EDITOR = _('L_MENU_EDITOR')
L_MENU_CREDITS = _('L_MENU_CREDITS')
L_MENU_QUIT = _('L_MENU_QUIT')
