<SelectableRecycleBoxLayout>

<SelectableLabel>
    canvas.before:
        Color:
            rgba: (0.5, 0.5, 0.5, 1)
        Rectangle:
            size: self.size
            pos: self.pos
        Color:
            rgba: (0, 0, 0.9, 1) if self.selected else (0, 0, 0.9, 0)
        Rectangle:
        	size: 3, self.height
        	pos: (self.x + self.width - 3, self.y)
    value: ''
    Label:
        text: root.value
